#!/bin/bash
# main — 容器状态检查脚本
# 功能：供 fnOS 框架调用，检查 AngeVoice 容器是否正常运行
set -e

FILE_PATH="${TRIM_APPDEST}/docker/docker-compose.yaml"

is_docker_running() {
    DOCKER_NAME=""

    if [ -f "${FILE_PATH}" ]; then
        DOCKER_NAME=$(grep "container_name" "${FILE_PATH}" | awk -F ':' '{print $2}' | xargs)
        echo "容器名称：${DOCKER_NAME}"
    fi

    if [ -n "${DOCKER_NAME}" ]; then
        docker inspect "${DOCKER_NAME}" | grep -q '"Status": "running",' || exit 1
        return
    fi
}

case $1 in
start)
    exit 0
    ;;
stop)
    exit 0
    ;;
status)
    if is_docker_running; then
        exit 0
    else
        exit 3
    fi
    ;;
*)
    exit 1
    ;;
esac
