"""moss admin configuration fields."""

from __future__ import annotations

from ..fields import AdminConfigField, field_def


FIELDS: tuple[AdminConfigField, ...] = (
    field_def(
        "moss_segment_length",
        "MOSS_SEGMENT_LENGTH",
        "MOSS 分句长度",
        "moss",
        "int",
        120,
        80,
        600,
        10,
        rebuild_moss=True,
        help="默认 120，牺牲少量吞吐换取中英文混合和长文本稳定；显存更充足时可切换长文本旁白预设。",
    ),
    field_def(
        "moss_voice_clone_max_text_tokens",
        "MOSS_VOICE_CLONE_MAX_TEXT_TOKENS",
        "MOSS token 上限",
        "moss",
        "int",
        56,
        20,
        200,
        1,
        rebuild_moss=True,
    ),
    field_def(
        "moss_max_new_frames",
        "MOSS_MAX_NEW_FRAMES",
        "MOSS 生成帧预算",
        "moss",
        "int",
        320,
        64,
        1200,
        1,
        rebuild_moss=True,
    ),
    field_def(
        "moss_max_silence_ms",
        "MOSS_MAX_SILENCE_MS",
        "最大静音",
        "moss",
        "float",
        480.0,
        0,
        5000,
        10,
        help="最终音频中超过该长度的静音会被压缩。",
    ),
    field_def(
        "moss_crossfade_ms",
        "MOSS_CROSSFADE_MS",
        "Crossfade",
        "moss",
        "float",
        12.0,
        0,
        120,
        1,
    ),
    field_def(
        "moss_segment_pause_ms",
        "MOSS_SEGMENT_PAUSE_MS",
        "段间停顿",
        "moss",
        "float",
        80.0,
        0,
        2000,
        10,
    ),
    field_def(
        "moss_runtime_pause_max_ms",
        "MOSS_RUNTIME_PAUSE_MAX_MS",
        "Runtime 停顿上限",
        "moss",
        "float",
        350.0,
        0,
        3000,
        10,
    ),
    field_def(
        "moss_output_target_peak",
        "MOSS_OUTPUT_TARGET_PEAK",
        "目标峰值",
        "moss",
        "float",
        0.86,
        0.1,
        1.0,
        0.01,
    ),
    field_def(
        "moss_output_gain",
        "MOSS_OUTPUT_GAIN",
        "输出增益",
        "moss",
        "float",
        0.94,
        0.1,
        2.0,
        0.01,
    ),
    field_def(
        "moss_audio_polish_enabled",
        "MOSS_AUDIO_POLISH_ENABLED",
        "音频自然化",
        "moss",
        "bool",
        True,
    ),
    field_def(
        "moss_trim_silence_enabled",
        "MOSS_TRIM_SILENCE_ENABLED",
        "裁剪首尾静音",
        "moss",
        "bool",
        True,
    ),
    field_def(
        "moss_mixed_english_policy",
        "MOSS_MIXED_ENGLISH_POLICY",
        "中英文混排",
        "moss",
        "choice",
        "translate",
        choices=(
            ("translate", "常见英文转自然中文"),
            ("preserve", "保留英文原文"),
            ("spell", "仅替换已知词组"),
        ),
        rebuild_moss=False,
        help="MOSS 对中文句子夹英文较敏感。默认 translate 会把 deadline、work-life balance 等常见词组转成中文，减少停顿、怪声和尾部漂移。",
    ),
    field_def(
        "moss_realtime_streaming_decode",
        "MOSS_REALTIME_STREAMING_DECODE",
        "逐帧流式",
        "moss",
        "bool",
        True,
        help="默认开启以保持 MOSS 官方逐帧流式体验；若特定设备出现边界噪声或显存压力，可在后台关闭。",
    ),
    field_def(
        "moss_stream_chunk_seconds",
        "MOSS_STREAM_CHUNK_SECONDS",
        "MOSS 分包秒",
        "moss",
        "float",
        0.40,
        0.05,
        2.0,
        0.01,
    ),
    field_def(
        "moss_stream_prebuffer_seconds",
        "MOSS_STREAM_PREBUFFER_SECONDS",
        "MOSS 预缓冲",
        "moss",
        "float",
        3.0,
        0,
        12.0,
        0.05,
        help="MOSS 长文本可能分段间隔较长，适当提高可减少播放中途断续。",
    ),
    field_def(
        "moss_stream_queue_max_items",
        "MOSS_STREAM_QUEUE_MAX_ITEMS",
        "MOSS 流式队列",
        "moss",
        "int",
        8,
        1,
        64,
        1,
    ),
    field_def(
        "moss_vram_guard_enabled",
        "MOSS_VRAM_GUARD_ENABLED",
        "启用显存保护",
        "moss",
        "bool",
        True,
        rebuild_moss=False,
        help="8GB 显存或家用 NAS 推荐开启。",
    ),
    field_def(
        "moss_vram_safe_free_mb",
        "MOSS_VRAM_SAFE_FREE_MB",
        "安全剩余显存 MB",
        "moss",
        "int",
        1200,
        0,
        65536,
        100,
    ),
    field_def(
        "moss_vram_critical_free_mb",
        "MOSS_VRAM_CRITICAL_FREE_MB",
        "临界剩余显存 MB",
        "moss",
        "int",
        600,
        0,
        65536,
        100,
    ),
    field_def(
        "moss_low_vram_segment_length",
        "MOSS_LOW_VRAM_SEGMENT_LENGTH",
        "低显存分句长度",
        "moss",
        "int",
        96,
        60,
        400,
        10,
    ),
    field_def(
        "moss_low_vram_max_new_frames",
        "MOSS_LOW_VRAM_MAX_NEW_FRAMES",
        "低显存帧预算",
        "moss",
        "int",
        280,
        64,
        800,
        1,
    ),
    field_def(
        "moss_low_vram_text_tokens",
        "MOSS_LOW_VRAM_TEXT_TOKENS",
        "低显存 token 上限",
        "moss",
        "int",
        48,
        20,
        160,
        1,
    ),
    field_def(
        "moss_disable_full_codec_after_oom",
        "MOSS_DISABLE_FULL_CODEC_AFTER_OOM",
        "OOM 后禁用整段解码",
        "moss",
        "bool",
        True,
    ),
    field_def(
        "moss_full_codec_oom_cooldown_seconds",
        "MOSS_FULL_CODEC_OOM_COOLDOWN_SECONDS",
        "OOM 冷却秒",
        "moss",
        "float",
        600.0,
        0,
        86400,
        10,
    ),
    field_def(
        "moss_vram_snapshot_ttl_seconds",
        "MOSS_VRAM_SNAPSHOT_TTL_SECONDS",
        "显存快照 TTL",
        "moss",
        "float",
        10.0,
        0,
        3600,
        1,
        help="缓存 torch/nvidia-smi 显存查询结果，减少长文本流式过程中的同步卡顿。0 表示每次都查。",
    ),
    field_def(
        "moss_hf_repo",
        "MOSS_HF_REPO",
        "MOSS HF 仓库",
        "moss",
        "str",
        "",
        restart=True,
        help="可选。默认留空并使用 ModelScope 仓库备用下载 MOSS ONNX 资产；如上游提供 Hugging Face 仓库，可在这里填写。",    advanced=True,
    ),
    field_def(
        "moss_prompt_audio_max_seconds",
        "MOSS_PROMPT_AUDIO_MAX_SECONDS",
        "参考音频秒数",
        "moss",
        "float",
        8.0,
        0,
        60,
        0.5,
        rebuild_moss=True,    advanced=True,
    ),
    field_def(
        "moss_output_peak_normalize_enabled",
        "MOSS_OUTPUT_PEAK_NORMALIZE_ENABLED",
        "峰值保护",
        "moss",
        "bool",
        True,    advanced=True,
    ),
    field_def(
        "moss_output_declick_enabled",
        "MOSS_OUTPUT_DECLICK_ENABLED",
        "去爆音",
        "moss",
        "bool",
        True,    advanced=True,
    ),
    field_def(
        "moss_output_edge_fade_ms",
        "MOSS_OUTPUT_EDGE_FADE_MS",
        "边缘淡入淡出",
        "moss",
        "float",
        1.5,
        0,
        20,
        0.5,    advanced=True,
    ),
    field_def(
        "moss_trim_silence_db",
        "MOSS_TRIM_SILENCE_DB",
        "静音阈值 dB",
        "moss",
        "float",
        -45.0,
        -90,
        -10,
        1,    advanced=True,
    ),
    field_def(
        "moss_quality_gate_enabled",
        "MOSS_QUALITY_GATE_ENABLED",
        "MOSS 质量自检",
        "moss",
        "bool",
        True,
        rebuild_moss=True,    advanced=True,
    ),
    field_def(
        "moss_process_isolation_enabled",
        "MOSS_PROCESS_ISOLATION_ENABLED",
        "MOSS 进程隔离",
        "moss",
        "bool",
        False,
        rebuild_moss=True,
        help="建议保持开启：超时或底层卡死时可终止隔离 worker 并自动恢复，避免引擎永久阻塞。",    advanced=True,
    ),
)
