"""Admin configuration profile presets."""

from __future__ import annotations


ADMIN_CONFIG_PROFILES: dict[str, dict[str, object]] = {
    "deploy_lan_default": {
        "label": "部署预设：局域网易用",
        "description": "适合家庭/NAS/内网，保留易访问体验并启用基础保护。",
        "values": {
            "public_status_endpoints": True,
            "trust_proxy_headers": False,
            "rate_limit_qps": 10.0,
            "rate_limit_burst": 20,
            "max_queue_length": 50,
            "websocket_max_connections": 16,
            "websocket_max_message_bytes": 33554432,
        },
    },
    "deploy_public_hardened": {
        "label": "部署预设：公网加固",
        "description": "公网暴露建议：收紧枚举接口并启用限流/队列保护。",
        "values": {
            "public_status_endpoints": False,
            "trust_proxy_headers": False,
            "rate_limit_qps": 3.0,
            "rate_limit_burst": 6,
            "max_queue_length": 64,
            "websocket_max_connections": 16,
            "websocket_max_message_bytes": 33554432,
        },
    },
    "nas_stable": {
        "label": "NAS 稳定",
        "description": "默认推荐：8GB 显存或家用 NAS，优先中英文混合稳定、减少卡顿和低音量。",
        "values": {
            "moss_segment_length": 120,
            "moss_voice_clone_max_text_tokens": 56,
            "moss_max_new_frames": 320,
            "moss_stream_chunk_seconds": 0.40,
            "moss_stream_queue_max_items": 8,
            "moss_stream_prebuffer_seconds": 3.0,
            "moss_max_silence_ms": 480,
            "moss_crossfade_ms": 12,
            "moss_segment_pause_ms": 80,
            "moss_runtime_pause_max_ms": 350,
            "moss_output_target_peak": 0.86,
            "moss_output_gain": 0.94,
            "moss_realtime_streaming_decode": True,
            "moss_vram_guard_enabled": True,
            "moss_apply_angevoice_rules": "auto",
            "moss_mixed_english_policy": "translate",
            "moss_vram_snapshot_ttl_seconds": 10.0,
        },
    },
    "nas_deep_sleep_cpu": {
        "label": "CPU 低配 NAS / Deep Sleep",
        "description": "低内存模式：降低缓存并在 180 秒空闲后释放当前模型；适用于内存受限设备，可结合彻底清理开关使用。",
        "values": {
            "model_idle_timeout_seconds": 180.0,
            "model_idle_check_interval": 30.0,
            "model_idle_unload_current": True,
            "restart_after_idle_unload_enabled": False,
            "cache_max_items": 16,
            "cache_max_bytes": 134217728,
            "cache_skip_text_over_chars": 400,
            "cache_skip_audio_over_bytes": 8388608,
            "max_concurrent_requests": 1,
        },
    },
    "balanced": {
        "label": "均衡推荐",
        "description": "10-12GB 显存或较强 CPU，兼顾自然度和稳定。",
        "values": {
            "moss_segment_length": 220,
            "moss_voice_clone_max_text_tokens": 80,
            "moss_max_new_frames": 400,
            "moss_stream_chunk_seconds": 0.50,
            "moss_stream_queue_max_items": 8,
            "moss_stream_prebuffer_seconds": 0.55,
            "moss_max_silence_ms": 650,
            "moss_crossfade_ms": 30,
            "moss_runtime_pause_max_ms": 600,
            "moss_realtime_streaming_decode": True,
        },
    },
    "long_narration": {
        "label": "长文本旁白",
        "description": "12GB+ 显存推荐：更自然；8GB 显存或内存受限设备不建议默认使用。",
        "values": {
            "moss_segment_length": 260,
            "moss_voice_clone_max_text_tokens": 90,
            "moss_max_new_frames": 450,
            "moss_stream_chunk_seconds": 0.55,
            "moss_stream_queue_max_items": 12,
            "moss_stream_prebuffer_seconds": 0.65,
            "moss_max_silence_ms": 760,
            "moss_crossfade_ms": 35,
            "moss_runtime_pause_max_ms": 650,
            "moss_realtime_streaming_decode": True,
        },
    },
    "low_latency": {
        "label": "低延迟流式",
        "description": "短句交互，首包更快。",
        "values": {
            "moss_segment_length": 120,
            "moss_voice_clone_max_text_tokens": 56,
            "moss_max_new_frames": 300,
            "moss_stream_chunk_seconds": 0.32,
            "moss_stream_queue_max_items": 8,
            "moss_stream_prebuffer_seconds": 0.55,
            "moss_crossfade_ms": 10,
            "moss_realtime_streaming_decode": True,
        },
    },
    "clone_quality": {
        "label": "克隆质量优先",
        "description": "16GB+ 推荐：首包更慢，克隆更稳。",
        "values": {
            "moss_segment_length": 240,
            "moss_voice_clone_max_text_tokens": 84,
            "moss_max_new_frames": 440,
            "moss_prompt_audio_max_seconds": 8.0,
            "moss_stream_chunk_seconds": 0.55,
            "moss_stream_prebuffer_seconds": 0.70,
            "moss_stream_queue_max_items": 8,
            "moss_max_silence_ms": 760,
            "moss_crossfade_ms": 35,
            "moss_realtime_streaming_decode": True,
        },
    },
}
