"""zipvoice admin configuration fields."""

from __future__ import annotations

from ..fields import AdminConfigField, field_def


FIELDS: tuple[AdminConfigField, ...] = (
    field_def(
        "zipvoice_process_isolation_enabled",
        "ZIPVOICE_PROCESS_ISOLATION_ENABLED",
        "ZipVoice 进程隔离",
        "zipvoice",
        "bool",
        False,
        rebuild_moss=True,
        advanced=True,
        help="正式 Docker/fnOS 部署默认开启。NAS/GPU 长驻部署请保持开启；关闭后使用 ZipVoice 产生的主机内存可能无法完整归还。",
    ),
    field_def(
        "zipvoice_num_steps",
        "ZIPVOICE_NUM_STEPS",
        "采样步数",
        "zipvoice",
        "int",
        8,
        1,
        32,
        1,
        help="步数提高可能改善质量但会增加延迟；CPU/NAS 建议先用 8，GPU 可测试 16。",
    ),
    field_def(
        "zipvoice_prompt_audio_max_seconds",
        "ZIPVOICE_PROMPT_AUDIO_MAX_SECONDS",
        "参考音频最长秒数",
        "zipvoice",
        "float",
        15.0,
        3.0,
        30.0,
        0.5,
        help="官方建议单人参考音频短于 3 秒；此项是产品保护上限，超过 3 秒只提示风险。",
    ),
    field_def(
        "zipvoice_remove_long_sil",
        "ZIPVOICE_REMOVE_LONG_SIL",
        "移除生成长静音",
        "zipvoice",
        "bool",
        False,
        help="仅在生成音频存在异常长停顿时尝试开启，可能改变自然停顿。",
    ),
    field_def(
        "zipvoice_guidance_scale",
        "ZIPVOICE_GUIDANCE_SCALE",
        "Guidance Scale",
        "zipvoice",
        "float",
        3.0,
        0.0,
        20.0,
        0.1,
        advanced=True,
    ),
    field_def(
        "zipvoice_t_shift",
        "ZIPVOICE_T_SHIFT",
        "T-Shift",
        "zipvoice",
        "float",
        0.5,
        0.01,
        1.0,
        0.01,
        advanced=True,
    ),
    field_def(
        "zipvoice_target_rms",
        "ZIPVOICE_TARGET_RMS",
        "目标 RMS",
        "zipvoice",
        "float",
        0.1,
        0.0,
        1.0,
        0.01,
        advanced=True,
    ),
    field_def(
        "zipvoice_feat_scale",
        "ZIPVOICE_FEAT_SCALE",
        "特征缩放",
        "zipvoice",
        "float",
        0.1,
        0.001,
        10.0,
        0.01,
        advanced=True,
    ),
)
